/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MandelbrotTest */

#ifndef _Included_MandelbrotTest
#define _Included_MandelbrotTest
#ifdef __cplusplus
extern "C" {
#endif
#undef MandelbrotTest_maxiters
#define MandelbrotTest_maxiters 999L
/*
 * Class:     MandelbrotTest
 * Method:    compute
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_MandelbrotTest_compute
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
