/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MandelbrotImpl */

#ifndef _Included_MandelbrotImpl
#define _Included_MandelbrotImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef MandelbrotImpl_maxiters
#define MandelbrotImpl_maxiters 999L
/*
 * Class:     MandelbrotImpl
 * Method:    compute
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_MandelbrotImpl_compute
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
